HOST: http://localhost:3000

--- Pubblico API v1 ---
---
Pubblico API
---

--
Conference resources
The following is a section of resources related to the conference
--
List all conferences.
GET /api/v1/conferences
< 200
< Content-Type: application/json
[{
    "id": "iccsw11",
    "shortName": "ICCSW'11",
    "longName": "2011 Imperial College Computing Student Workshop",
    "dates": { "from": "2011-09-29T9:00:00.000Z" , "to": "2011-09-30T17:00:00.000Z" },
    "description": "The 2011 Imperial College Computing Student Workshop aims to provide an international forum for doctoral students to discuss a range of topics that are current in computer science research. The workshop welcomes all research students in the field of computer science."
},
{
    "id": "iccsw12",
    "shortName": "ICCSW'12",
    "longName": "2012 Imperial College Computing Student Workshop",
    "dates": { "from": "2012-09-27T9:00:00.000Z" , "to": "2012-09-28T17:00:00.000Z" },
    "description": "The 2012 Imperial College Computing Student Workshop aims to provide an international forum for doctoral students to discuss a range of topics that are current in computer science research. The workshop welcomes all research students in the field of computer science."
},
{
    "id": "iccsw13",
    "shortName": "ICCSW'13",
    "longName": "2013 Imperial College Computing Student Workshop",
    "dates": { "from": "2013-09-26T9:00:00.000Z" , "to": "2013-09-27T17:00:00.000Z" },
    "description": "The 2013 Imperial College Computing Student Workshop aims to provide an international forum for doctoral students to discuss a range of topics that are current in computer science research. The workshop welcomes all research students in the field of computer science."
}]

Conference public metadata.
GET /api/v1/conferences/{conference}
< 200
< Content-Type: application/json
{
    "id": "iccsw13",
    "shortName": "ICCSW'13",
    "longName": "2013 Imperial College Computing Student Workshop",
    "dates": { "from": "2013-09-26T9:00:00.000Z" , "to": "2013-09-27T17:00:00.000Z" },
    "description": "The 2013 Imperial College Computing Student Workshop aims to provide an international forum for doctoral students to discuss a range of topics that are current in computer science research. The workshop welcomes all research students in the field of computer science."
}

--
Conference detail resources
The following is a section of resources related to the details of a conference
--
List all submissions of a conference.
GET /api/v1/conferences/{conference}/submissions
< 200
< Content-Type: application/json
[{
    "id": 1,
    "title": "Towards the Improvement of Randomized Algorithms",
    "abstract": "The implications of permutable communication have been far-reaching and pervasive. This follows from the understanding of agents [21]. Given the current status of distributed algorithms, electrical engineers compellingly desire the evaluation of IPv7. In order to realize this goal, we describe a novel system for the construction of systems (Ecchymosis), showing that spreadsheets and RPCs [21] are generally incompatible.",
    "authors": [{
        "affiliation" : "University of Example",
        "email" : "example@example.edu",
        "name": {
            "last": "LAST",
            "first": "FIRST"
        }
    },{
        "affiliation" : "University of Exampl22222e",
        "email" : "example2@example.edu",
        "name": {
            "last": "LAST222",
            "first": "FIRST11111"
        }
    }],
    "submitted": "2013-02-04T10:18:28.531Z",
    "lastUpdated": "2013-02-04T10:18:28.531Z",
    "tags": ["network", "agents"],
    "bids": [{
        "user": "user1",
        "selection": "conflict"
    }]
},
{
    "id": 2,
    "title": "The Effect of Electronic Modalities on Cryptography",
    "abstract": "Cyberneticists agree that compact methodologies are an interesting new topic in the field of e-voting technology, and cyberinformaticians concur. In fact, few end-users would disagree with the study of XML. in this position paper we show not only that compilers and symmetric encryption are often incompatible, but that the same is true for web browsers [3].",
    "authors": [{
        "affiliation" : "University of Wolf",
        "email": "lone@user.edu",
        "name" : {
            "first" : "lone",
            "last" : "user"
        }
    }],
    "submitted": "2013-02-07T12:53:22.531Z",
    "lastUpdated": "2013-02-08T15:22:56.531Z",
    "tags": ["cryptography", "modality"],
    "bids": [{
        "user": "nickng@doc.ic.ac.uk",
        "selection": "yes"
    },{
        "email": "petrh@example.com",
        "selection": "no"
    },{
        "user": "florian@example.edu",
        "selection": "maybe"
    }]
}]

Get a submission of a conference.
GET /api/v1/conferences/{conference}/submissions/{submission}
< 200
< Content-Type: application/json
{
    "id": 1,
    "title": "Towards the Improvement of Randomized Algorithms",
    "abstract": "The implications of permutable communication have been far-reaching and pervasive. This follows from the understanding of agents [21]. Given the current status of distributed algorithms, electrical engineers compellingly desire the evaluation of IPv7. In order to realize this goal, we describe a novel system for the construction of systems (Ecchymosis), showing that spreadsheets and RPCs [21] are generally incompatible.",
    "authors": [{
        "affiliation" : "University of Example",
        "email" : "example@example.edu",
        "name": {
            "last": "LAST",
            "first": "FIRST"
        }
    },{
        "affiliation" : "University of Exampl22222e",
        "email" : "example2@example.edu",
        "name": {
            "last": "LAST222",
            "first": "FIRST11111"
        }
    }],
    "submitted": "2013-02-04T10:18:28.531Z",
    "lastUpdated": "2013-02-04T10:18:28.531Z",
    "tags": ["network", "agents"],
    "bids": [{
        "user": "nickng@examp.le",
        "selection": "conflict"
    }],
    "reviews": [{
        "reviewer": {
            "email": "reviewer@example.edu",
            "name": {
                "first": "Name",
                "last": "Surname"
            }
        },
        "score": 0.8,
        "qualification": 0.6,
        "summary": "Really nice paper",
        "strengths": "Lots of nice stuff",
        "weaknesses": "Lots of bad stuff",
        "reviewed": "2013-02-05T10:18:28.531Z"
    }, {
        "reviewer": {
            "email": "reviewer2@example.edu",
            "name": {
                "first": "Name",
                "last": "Surname"
            }
        },
        "score": 0.6,
        "qualification": 0.75,
        "summary": "Could have been better",
        "strengths": "Not so amazing",
        "weaknesses": "Not so bad either",
        "reviewed": "2013-02-05T10:19:28.531Z"
    }],
    "comments": [{
        "commenter": {
            "email": "hello@world.com"
        },
        "comment": "I really like this paper!",
        "commented": "2013-02-06T10:18:28.531Z"
    }]
}

List all submitters and intended submitters.
GET /api/v1/conferences/{conference}/submitters
< 200
< Content-Type: application/json
[{
    "affiliation": "Example University",
    "emails": [ "foobar@example.edu" ],
    "name": {
        "first": "Foo",
        "last": "Bar"
    }
},
{
    "emails": [ "organiser@example.edu", "organiser@example.ac.uk" ],
    "affiliation": "Example University",
    "name": {
        "first": "Organ",
        "last": "Iser"
    },
    "active": true
}]

List of conference organisers for users to find the contacts of a conference.
GET /api/v1/conferences/{conference}/organisers
< 200
< Content-Type: application/json
[{
    "emails": [ "foobar@example.edu" ],
    "affiliation": "Example University",
    "name": {
        "first": "Foo",
        "last": "Bar"
    },
    "active": true
}]
